/*
 * Generated by MTK SP Drv_CodeGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Mar  4 09:18:18 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


